name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci-cd:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Start database containers
      run: docker-compose -f "kbe/docker-compose.yml" up -d warehouse-db-mysql product-db-mysql product-db-mongo
      
    - name: Build with Maven
      run: mvn -f kbe/pom.xml clean package
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "kbe/docker-compose.yml" down

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

      
    - name: Build and Push Product Image
      uses: docker/build-push-action@v2
      id: docker_build_product
      with:
        context: ./kbe/product/
        file: ./kbe/product/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/product
        
    - name: Build and Push Currency Image
      uses: docker/build-push-action@v2
      id: docker_build_currency
      with:
        context: ./kbe/currency/
        file: ./kbe/currency/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/currency
        
    - name: Build and Push Warehouse Image
      uses: docker/build-push-action@v2
      id: docker_build_warehouse
      with:
        context: ./kbe/warehouse/
        file: ./kbe/warehouse/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/warehouse
        
    - name: Build and Push Price Image
      uses: docker/build-push-action@v2
      id: docker_build_price
      with:
        context: ./kbe/price/
        file: ./kbe/price/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/price
        
    - name: Build and Push Gateway Image
      uses: docker/build-push-action@v2
      id: docker_build_gateway
      with:
        context: ./kbe/gateway/
        file: ./kbe/gateway/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gateway
        
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v2
      id: docker_build_frontend
      with:
        context: ./kbe/frontend/
        file: ./kbe/frontend/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
        
    - name: Verify
      run: echo ${{ steps.docker_build.outputs.digest }}
